network:
  interfaces: ["all"]
  monitoring_interval: 0.1
  max_connections: 10000

protection:
  packet_threshold: 1000
  time_window: 1.0
  block_duration: 3600
  min_threat_level: 80
  max_packets_per_ip: 500
  max_bandwidth_per_ip: 10485760

detection:
  syn_flood:
    enabled: true
    threshold: 800
  udp_flood:
    enabled: true
    threshold: 1000
  http_flood:
    enabled: true
    threshold: 500
  volumetric:
    enabled: true
    threshold: 1048576

whitelist:
  ips: [
    "127.0.0.1",
    "192.168.1.1"
  ]
  networks: [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16"
  ]

advanced:
  memory_limit: 1073741824
  cpu_threshold: 80
  log_level: "INFO"
  cleanup_interval: 300
  rate_limit:
    enabled: true
    requests: 1000
    period: 60 